spring:
  application:
    name: arca-server

  datasource:
    url: jdbc:mysql://localhost:3306/arca?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: arca
    password: arca

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
