spring:
  application:
    name: arca-server

  datasource:
    url: jdbc:mysql://localhost:3306/arca?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: arca
    password: arca

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    locations:
      - classpath:database/migration
      - classpath:database/seed

cors:
  allowed-origins:
    - http://localhost:5173

auth-session:
  ttl: 24h

logging:
  pattern:
    correlation: "[%X{requestId}] "
